### ISSUE TITLE
Shap values for XGBoost Classifier as probabilities

### ISSUE THREAD

**Issue by Jurgita-DS** [micahmelling/parallel-shap#1]
Hi, I was wondering if there is a way to obtain shap values for XGBoost Classifier expressed as probabilities? It looks like they are displayed in different units by default since the values go beyond [0, 1] range.

**Comment by micahmelling** [comment]
Sorry for the delay in responding! I think this should be possible. Let me check into it and report back.

**Comment by micahmelling** [comment]
@Jurgita-DS, I have released auto-shap 0.2.1. In this version, boosting classifiers will automatically have the SHAP values in probabilities rather than log odds. I hope this helps! Let me know if you run into any issues.

https://pypi.org/project/auto-shap/

**Comment by Jurgita-DS** [comment]
@micahmelling that's great, thank you! I will test it in the next couple of weeks.
