### ISSUE TITLE
TypeError when using auto-shap on Naive Bayes models or SVC models

### ISSUE THREAD

**Issue by conge** [micahmelling/parallel-shap#2]
Hi,

I enjoy auto-shap for it simplied my workflow a lot. thank you for the great work!

Recectly I was playing with Naive Bayes models (e.g. sklearn.naive_bayesBernoulliNB ) and SVC models (sklearn.svm.SVC), the auto-shap failed on me by giving the following TypeError. :

> 
> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> /var/folders/ns/fwk51rq51_92t1bw24g3136cq5vk8m/T/ipykernel_40545/67005119.py in <module>
>       2 shap_dir = inputdir + 'shap_output/'
>       3 save_path = shap_dir + tag
> ----> 4 produce_shap_values_and_summary_plots(model=model, x_df=shap_df_train, save_path=save_path,n_jobs=10)
> 
> ~/opt/miniconda3/envs/brain_ai/lib/python3.9/site-packages/auto_shap/auto_shap.py in produce_shap_values_and_summary_plots(model, x_df, save_path, linear_model, tree_model, boosting_model, calibrated_model, regression_model, voting_or_stacking_model, use_kernel, file_prefix, n_jobs)
>     338         ]
>     339     )
> --> 340     shap_values_df, shap_expected_value, global_shap_df = generate_shap_values(
>     341         model, x_df, linear_model, tree_model, boosting_model, calibrated_model, regression_model,
>     342         voting_or_stacking_model, use_kernel, n_jobs
> 
> ~/opt/miniconda3/envs/brain_ai/lib/python3.9/site-packages/auto_shap/auto_shap.py in generate_shap_values(model, x_df, linear_model, tree_model, boosting_model, calibrated_model, regression_model, voting_or_stacking_model, use_kernel, n_jobs)
>     287             voting_or_stacking_model
>     288         )
> --> 289     shap_values_df, shap_expected_value, global_shap_df = produce_raw_shap_values(
>     290         model, x_df, use_kernel, linear_model, tree_model, calibrated_model, boosting_model, regression_model,
>     291         voting_or_stacking_model, n_jobs
> 
> TypeError: cannot unpack non-iterable NoneType object
> 

Could you please take look at this?

Thanks,

Yang

**Comment by micahmelling** [comment]
Sorry for the issue! An interim solution would be to turn on the Kernel Explainer, which is model agnostic.

produce_shap_values_and_summary_plots(model=model, x_df=shap_df_train, save_path=save_path, use_kernel=True)

However, the Kernel Explainer can be slow, so you might want to subset the x_df.

Here's what I'll do in an upcoming release. First, I want to replace the Kernel Explainer with a faster model-agnostic alternative (probably the Partition Explainer). Second, I should have auto-shap fallback on the model-agnostic explainer for any type of model it doesn't "know" (such as the two you mentioned).

**Comment by micahmelling** [comment]
@conge, I have released auto-shap 0.2.1 to address this issue. Any time we cannot use a specialized explainer, like the tree explainer, we will fallback to the kernel explainer.

https://pypi.org/project/auto-shap/

**Comment by conge** [comment]
> Sorry for the issue! An interim solution would be to turn on the Kernel Explainer, which is model agnostic.
> 
> produce_shap_values_and_summary_plots(model=model, x_df=shap_df_train, save_path=save_path, use_kernel=True)
> 
> However, the Kernel Explainer can be slow, so you might want to subset the x_df.
> 
> Here's what I'll do in an upcoming release. First, I want to replace the Kernel Explainer with a faster model-agnostic alternative (probably the Partition Explainer). Second, I should have auto-shap fallback on the model-agnostic explainer for any type of model it doesn't "know" (such as the two you mentioned).

I want to propose a possible solution to the "the Kernel Explainer can be slow" problem. It look something like this:

```
def produce_shap_output_with_agnostic_explainer(model: callable, x_df: pd.DataFrame, boosting_model: bool,
                                                regression_model: bool, linear_model: bool,
                                                return_df: bool = True, n_jobs: int = None, 
                                                sample_size: int = None, k: int = None) -> tuple:

    # Initialize background samples for the SHAP explainer. Data will be subsampled if  sample_size or k is provided.
    if sample_size:        
        background_samples = shap.sample(x_df, sample_size)  # Use randomly sampled background samples
    elif k:
        # Initialize the SHAP explainer with reduced background samples
        background_samples = shap.kmeans(x_df, k)  # Use k-means summarized background samples
    else:
         background_samples = x_df
     
if regression_model:
        explainer = shap.KernelExplainer(model.predict, background_samples)
else:
        explainer = shap.KernelExplainer(model.predict_proba, background_samples)

# Calculate SHAP values for all samples

```

What do you think?

**Comment by micahmelling** [comment]
I like this idea a lot. I will work to get this functionality in the next release. Thank you!

**Comment by micahmelling** [comment]
I have made an update in version 0.3.0 to reflect this suggestion! (Slight modifications). Thank you so much for the help on this.
